# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7fb0f67130d61197555a28ab0f5924cce0a4abd00d4daa99f816cea47d28a8c436391f3f1792215160f015913dd3f8fd1713c4cde759b8a2b5de46df4d69dd5

test:
  secret_key_base: fd6ec3e82371a30535dc5797ccecd447541097715f26aca14d705f265f462ab1b7de5c7eda6bff6948bcdc0918d8b0dede66f2916fa48bf47bfdd0ee3b119686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
